title: vineeshvs
description: Final year M.Tech + Ph.D. Dual Degree student at the department of Electrical Engineering, IIT Bombay, India.
show_downloads: false
google_analytics:
theme: jekyll-theme-architect